var _ = require("lodash");
var AlchemyDataNewsV1 = require('watson-developer-cloud/alchemy-data-news/v1');
var alchemyDataNews = new AlchemyDataNewsV1({
    api_key: process.env.ALCHEMY_API_KEY
});

function AlchemyData(app) {
    this.app = app;
    this.app.ee.on('AlchemyDataGet', this.get);
    this.app.ee.on('AlchemyDataShow', this.show);
}


AlchemyData.prototype.get = function (eventObj) {

    var params = {
        start: 'now-1h',
        end: 'now',
        outputMode: 'json',
        count: 5,
        return: 'enriched.url.title,enriched.url.text,enriched.url.author,original.url',
        q: 'q.enriched.url.entities.entity.text=O[USA^Pakistan^Islamabad]'

    };

    // alchemyDataNews.getNews(params, function (err, news) {
    //     var result = null;
    //     if (err) {
    //         result = err;
    //         console.error('AlchemyData:', 'error:', err);
    //
    //     } else {
    //         result = news;
    //         console.info('AlchemyData:', news);
    //
    //     }
    //
    //     return (_.isFunction(eventObj.cb)) ? eventObj.cb(result) : '';
    // });

    var resultJson = {
        "status": "OK",
        "usage": "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html",
        "totalTransactions": "10",
        "result": {
            "docs": [
                {
                    "id": "MTU2ODM5Mjg4Njl8MTQ3ODg4OTA5NA",
                    "source": {
                        "enriched": {
                            "url": {
                                "author": "",
                                "text": "Good points NC. I haven't seen a ton of changes from Chips offense either. Granted I haven't been able to really dig into the all22 that I usually enjoy watching. ...",
                                "title": "The Official I HATE Trent Baalke Thread | Page 2945"
                            }
                        },
                        "original": {
                            "url": "http://www.49erswebzone.com/forum/niners/159134-official-hate-trent-baalke-thread/page2945/"
                        }
                    },
                    "timestamp": 1478889094
                },
                {
                    "id": "MTU2ODM5Mjg4Njl8MTQ3ODg4OTA5NA",
                    "source": {
                        "enriched": {
                            "url": {
                                "author": "",
                                "text": "Good points NC. I haven't seen a ton of changes from Chips offense either. Granted I haven't been able to really dig into the all22 that I usually enjoy watching. ...",
                                "title": "The Official I HATE Trent Baalke Thread | Page 2945"
                            }
                        },
                        "original": {
                            "url": "http://www.49erswebzone.com/forum/niners/159134-official-hate-trent-baalke-thread/page2945/"
                        }
                    },
                    "timestamp": 1478889094
                },
                {
                    "id": "MTU2ODM5Mjg4Njl8MTQ3ODg4OTA5NA",
                    "source": {
                        "enriched": {
                            "url": {
                                "author": "",
                                "text": "Good points NC. I haven't seen a ton of changes from Chips offense either. Granted I haven't been able to really dig into the all22 that I usually enjoy watching. ...",
                                "title": "The Official I HATE Trent Baalke Thread | Page 2945"
                            }
                        },
                        "original": {
                            "url": "http://www.49erswebzone.com/forum/niners/159134-official-hate-trent-baalke-thread/page2945/"
                        }
                    },
                    "timestamp": 1478889094
                },
                {
                    "id": "MTU2ODM5Mjg4Njl8MTQ3ODg4OTA5NA",
                    "source": {
                        "enriched": {
                            "url": {
                                "author": "",
                                "text": "Good points NC. I haven't seen a ton of changes from Chips offense either. Granted I haven't been able to really dig into the all22 that I usually enjoy watching. ...",
                                "title": "The Official I HATE Trent Baalke Thread | Page 2945"
                            }
                        },
                        "original": {
                            "url": "http://www.49erswebzone.com/forum/niners/159134-official-hate-trent-baalke-thread/page2945/"
                        }
                    },
                    "timestamp": 1478889094
                },
                {
                    "id": "MTU2ODM5Mjg4Njl8MTQ3ODg4OTA5NA",
                    "source": {
                        "enriched": {
                            "url": {
                                "author": "",
                                "text": "Good points NC. I haven't seen a ton of changes from Chips offense either. Granted I haven't been able to really dig into the all22 that I usually enjoy watching. ...",
                                "title": "The Official I HATE Trent Baalke Thread | Page 2945"
                            }
                        },
                        "original": {
                            "url": "http://www.49erswebzone.com/forum/niners/159134-official-hate-trent-baalke-thread/page2945/"
                        }
                    },
                    "timestamp": 1478889094
                },
                {
                    "id": "MTU2ODM5Mjg4Njl8MTQ3ODg4OTA5NA",
                    "source": {
                        "enriched": {
                            "url": {
                                "author": "",
                                "text": "Good points NC. I haven't seen a ton of changes from Chips offense either. Granted I haven't been able to really dig into the all22 that I usually enjoy watching. ...",
                                "title": "The Official I HATE Trent Baalke Thread | Page 2945"
                            }
                        },
                        "original": {
                            "url": "http://www.49erswebzone.com/forum/niners/159134-official-hate-trent-baalke-thread/page2945/"
                        }
                    },
                    "timestamp": 1478889094
                }
            ],
            "next": "NTEwMDY0NjA1NzQ5NzMxMTA2NHx8MTU0Mzk3MTUxNTY4MjEzMjY5MDV8fDE2OTE3ODI2NDgyMjM0MTY5MjAwfHwxNzkzNDk0NDUyNjExNDE0NTcyMXxNVFUyT0RNNU1qZzROamw4TVRRM09EZzRPVEE1TkE",
            "status": "OK"
        }
    };
    return (_.isFunction(eventObj.cb)) ? eventObj.cb(resultJson) : '';
};


AlchemyData.prototype.show = function (eventObj) {

    return (_.isFunction(eventObj.cb)) ? eventObj.cb({all: 'well'}) : '';
};


module.exports = AlchemyData;